CREATE TABLE artists (
    artist_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    artist_name varchar(255) NOT NULL UNIQUE,
    birthday DATE NOT NULL,
    birthplace varchar(255) NOT NULL,
    is_alive BOOLEAN NOT NULL DEFAULT 'true'
);